name: tokudane-check

on:

 schedule:
  - cron: "*/10 * * * *"

 workflow_dispatch:

jobs:

 run:

  runs-on: ubuntu-latest

  steps:

  - uses: actions/checkout@v3

  - uses: actions/setup-python@v4
    with:
      python-version: "3.11"

  - run: pip install -r requirements.txt

  - run: playwright install

  - run: python check_tokudane.py
    env:
      LINE_CHANNEL_TOKEN: ${{ secrets.LINE_CHANNEL_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}